### ISSUE TITLE
Create Java Program to print inverted pyramid

### ISSUE THREAD

**Issue by Balaji3049** [CreatorsAcademy/Programming#1]
Create Java Program to print inverted pyramid
## Expected Output
![image](https://github.com/user-attachments/assets/cdde19d1-1e2e-46a4-8374-12957ad67fea)

**Comment by syamkumardamarla** [comment]
https://github.com/CreatorsAcademy/Programming/pull/4

**Comment by Balaji3049** [comment]
Changes are merged
